// 1. IMPORTS
import React from 'react';
import { Stack } from 'expo-router';
import { useTheme } from '../../theme';

// 2. TYPES

/** Configuration for a single toolbar action button using SF Symbols. */
export interface NativeHeaderAction {
  /** SF Symbol name (e.g. 'sidebar.right') */
  icon: string;
  /** Press handler for the action */
  onPress?: () => void;
  /** Tint color override. Defaults to theme.onSurface */
  tintColor?: string;
}

/**
 * Props for the NativeHeader component.
 *
 * @example
 * ```tsx
 * <NativeHeader
 *   title="Explore"
 *   trailing={[{ icon: 'sidebar.right', onPress: toggleSidebar }]}
 * />
 * ```
 */
export interface NativeHeaderProps {
  /** Header title text */
  title?: string;
  /** Whether the header is visible. @default true */
  headerShown?: boolean;
  /** Whether the back button is visible. @default true */
  headerBackVisible?: boolean;
  /** Actions displayed on the leading (left) side of the header */
  leading?: NativeHeaderAction[];
  /** Actions displayed on the trailing (right) side of the header */
  trailing?: NativeHeaderAction[];
  /** Stack.Screen children (auto-generated by expo-router) */
  children?: React.ReactNode;
}

// 3. COMPONENT

/**
 * iOS-native header component wrapping expo-router's Stack with Stack.Toolbar.
 *
 * Applies M3 theme colors automatically and renders SF Symbol toolbar buttons
 * via the native Stack.Toolbar API. Import this component in `.ios.tsx` files only.
 */
const NativeHeader = ({
                                title,
                                headerShown = true,
                                headerBackVisible = true,
                                leading,
                                trailing,
                                children,
                              }: NativeHeaderProps) => {
  const theme = useTheme();

  return (
      <Stack
          screenOptions={{
            headerShown,
            headerTitle: title,
            headerStyle: {
              backgroundColor: theme.tokens.appbar.background,
            },
            headerTintColor: theme.onSurface,
            headerBackVisible,
          }}
      >
        {children}
        {trailing && trailing.length > 0 && (
            <Stack.Toolbar placement="right">
              {trailing.map((action, index) => (
                  <Stack.Toolbar.Button
                      key={index}
                      icon={'arrow.2.circlepath'}
                      onPress={action.onPress}
                      tintColor={action.tintColor ?? theme.onSurface}
                  />
              ))}
            </Stack.Toolbar>
        )}
        {leading && leading.length > 0 && (
            <Stack.Toolbar placement="left">
              {leading.map((action, index) => (
                  <Stack.Toolbar.Button
                      key={index}
                      icon={'arrow.backward'}
                      onPress={action.onPress}
                      tintColor={action.tintColor ?? theme.onSurface}
                  />
              ))}
            </Stack.Toolbar>
        )}
      </Stack>
  );
};

NativeHeader.displayName = 'NativeHeader';

// 4. STYLES
// No custom styles — styling is handled by Stack screenOptions and native toolbar.

// 5. EXPORTS
export { NativeHeader };
